### PR TITLE
Request merge of Game logic into develop

### PR DESCRIPTION
**Pull request by ershadul1**
### Project Specification
- Created logic for tic tac toe game 
- Used OOP to implement different logic of the game
- Considered edge cases. e.g. if a players input is invalid it will not continue

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ershadul1  and @rahalrazika, great job with this amazing project :+1: Code looks clean :100: PR has a short description of the project :1st_place_medal: Great job applying the single responsibility rule for our methods. However, to get our project approved, we need to address the following comments:
- The game outputs a `draw` instead of a `win` as in the screenshot below.  It is not finding the winning combination of the diagonal values
bug
- Let us separate the 2 classes in the `lib/methods.rb` file. We can create a file for both classes, it is not a good practice to have 2 classes in the same file. Also, it will be difficult to test
class

Kindly fix these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: :woman_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Comment by ershadul1** [comment]
Changes made as per the review.
- Created separate files for each class
- Fixed the problem with the game result

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @ershadul1 & @rahalrazika   :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- [x] Kindly before we wrap up things, let's ensure we have removed all the inline comments in our codebase from the previous milestone. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/no_comment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by rahalrazika** [comment]
Changes made as per the review
- remove the comments

**Comment by Anna-Myzukina** [comment]
# [APPROVED]  :heavy_check_mark: 

## Thanks for applying the changes  :+1:

### Go and merge to `develop`.

# :raising_hand:  See you at the next projects.

Happy coding  <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Pull request merged**
